### PR TITLE
Ethernet - standard MACAddress getter with a parameter

### PR DESCRIPTION
**Pull request by JAndrassy**
MACAddress getter as in other Ethernet library

[overview](https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#legacy-ethernet-getters-and-setters) of legacy Ethernet specific getters and setters in libraries

### CODE REVIEW

**Comment by aentinger** [comment]
Why not

```C++
void CEthernet::MACAddress(uint8_t *mac) {
  CLwipIf::getInstance().getMacAddress(NI_ETHERNET, mac);
}
```
?

**Comment by JAndrassy** [comment]
> Why not?

so the mac_address field is filled too

**Comment by aentinger** [comment]
>I change the PR.

Please do :pray: :bow: .

**Comment by JAndrassy** [comment]
modified

**Review by aentinger — APPROVED** [review]
LGTM :+1:

**Pull request merged**
