### PR TITLE
Add AES encrypt/decrypt support for SE05X on Arduino with two example sketches

### PR DESCRIPTION
**Pull request by jowin202**
Hello,

I used the se05x_APDU_apis.h function for block cipher to implement a demonstration example sketch for AES encryption and decryption. I found AES encryption with secure element nowhere (looked for days/hours) and decieded to do it by myself.

Please add this

kind regards

### CODE REVIEW

**Comment by jowin202** [comment]
How to sign the license agreement?

**Comment by jowin202** [comment]
OK, the building process failed with

```
'class SE05XClass' has no member named 'AES_ECB_encrypt'
'class SE05XClass' has no member named 'AES_ECB_decrypt'
'class SE05XClass' has no member named 'writeAESKey'; did you mean 'writeSlot'?
```

but this are exactly the 3 functions I added to SE05X.c / SE05X.h library.

**Comment by facchinm** [comment]
@jowin202 test failures on the stable version `arduino:renesas_portenta:portenta_c33` are expected (since the APIs are not there yet :wink: ). The test that shouldn't fail (and passes indeed) is on `arduino-git:renesas:portenta_c33`
Waiting for @pennam review but it looks good to me :+1:

**Review by pennam — APPROVED** [review]
Tested and works as expected. Thanks @jowin202

**Comment by jowin202** [comment]
Hello,
Just a question: Will this pull request be merged into the original repository (and when)? I would like to do another pull request for HMAC support, but I'm not familiar with github and the branch-things. So I would like to clear my fork and make a completely new pull request.
Kind regards

**Comment by jowin202** [comment]
Oh I see the changes are already here now. Yes, I added HMAC to my personal fork, but I don't know if this is working and ready for being included into the main branch.

**Comment by pennam** [comment]
Ok, so i will take  your first two commits open a new pr and merge them into main. After that when code is ready you can open a new PR for HMAC support.

**Comment by jowin202** [comment]
Ahh ok. I have 2 commits in this pull request

add AES:       2f96751419e9a012eb0531a6468f3e9d13b64c6c
add HMAC:  336826e0cf2254a6e490608b25541a2ed8cb99c9

Hopefully they can be included into the arduino lib

**Comment by pennam** [comment]
is also https://github.com/arduino/ArduinoCore-renesas/commit/336826e0cf2254a6e490608b25541a2ed8cb99c9 ready? It was not included in the original PR and i've understood you are not sure it is working.

>  Yes, I added HMAC to my personal fork, but I don't know if this is working and ready for being included into the main branch.

**Comment by jowin202** [comment]
> is also [336826e](https://github.com/arduino/ArduinoCore-renesas/commit/336826e0cf2254a6e490608b25541a2ed8cb99c9) ready? It was not included in the original PR and i've understood you are not sure it is working.
> 
> > Yes, I added HMAC to my personal fork, but I don't know if this is working and ready for being included into the main branch.

It’s also ready from my side. I haven’t figured out how to make a new pull request.

**Pull request closed without merging**
