### PR TITLE
Wire: fix setClock

### PR DESCRIPTION
**Pull request by facchinm**
clock source is fixed for RA4M1, so the rates will be wrong for C33.
This will be fixed in the next commit

### CODE REVIEW

**Comment by mjs513** [comment]
@facchinm 
Have a question on the settings that you are using for 400khz.  If I attach a Logic analyzer to SDA/SCL while running a sketch pulling data from a MPU-9250 I am seeing:
Minima400currentSettings
which I believe is showing a frequency of about 257khz not close to the 400khz.  

However if I change your settings to:
```
          m_i2c_extend.clock_settings.brl_value = 12;
          m_i2c_extend.clock_settings.brh_value = 11;
          m_i2c_extend.clock_settings.cks_value = 0;
```
I get closer to 400khz (357khz):
Minima400mysettings

**Comment by mjs513** [comment]
@facchinm
These settings work better - gives 400khz with 60% duty cycle
```
        case I2C_MASTER_RATE_FAST:
          m_i2c_extend.clock_settings.brl_value = 16;
          m_i2c_extend.clock_settings.brh_value = 15;
          m_i2c_extend.clock_settings.cks_value = 0;
```

**Comment by greiman** [comment]
setClock should not only allow the three values, 100kHz, 400kHz, 1Mhz.  See  [this](https://github.com/arduino/ArduinoCore-renesas/issues/68) issue.

**Comment by facchinm** [comment]
@mjs513 @greiman I pushed a new version of the patch which should take care of the clocks for both UNO and C33.
In this patch I explicitly disabled FAST_MODE_PLUS for platforms not supporting it (eg. RA4M1) so we are in the specifications of the chip.
Let me know if it works for you, then we can merge it safely.

**Comment by mjs513** [comment]
@facchinm 
Got some strange things happening when testing the changes at 400khz.
Using a 5v liquidCrystal_i2c device on Wire with your current settings of 16/15 I am seeing 500khz using a LA:
Screenshot 2023-08-04 144853
If I change the settings for 400khz to 22/21 I am seeing 400khz, again for 5v device on Wire:
Screenshot 2023-08-04 145134

But if I use those settings 22/21 for a MPU-9250 running at 3.3v on Wire I am seeing something like 257khz
Screenshot 2023-08-04 145849

Using your settings, again on wire for a MPU-9250 I am getting 294khz:
Screenshot 2023-08-04 150222

Confused!!!!!!

And if I move the 9250 over to Wire1 using your settings of 16/15 I am seeing that 526khz again
Screenshot 2023-08-04 150740

and if I use the 22/21 settings I am seeing 416khz at 52% duty cycle.

So now I am confused.  Please note I do have the Micros propose PR incorporated as well as a couple of others.

**Comment by mjs513** [comment]
@facchinm 
out of curiosity I pulled out a T4.1 (had it handy) and check 100khz and 400khz.  At 100khz seeing 68khz with 50% while at 400khz I am seeing 357khz clock with 50% duty cycle for my MPU-9250. 

Never one to leave enough alone:
Adafruit Metro M0 express: 97khz with 50% duty at 100Khz; 357khz with 50% duty at 400khz
Uno R3 Clone:  370khz with 52% duty at 400khz;  100khz with 49% duty at 100khz setclock.

**Comment by greiman** [comment]
Wire1 has level shifters and works correctly for 3V3 devices.  Wire is marginal for 3V3 devices.  For 3V3 devices on Wire, the speed depends on pull-up resistance, pull-up voltage, and VCC for the RA4M1.  See [this](https://github.com/arduino/ArduinoCore-renesas/issues/69#issuecomment-1656023777).

**Comment by mjs513** [comment]
@facchinm -  just wanted to know if there was anything else you wanted me to try with this?

**Comment by mjs513** [comment]
@facchinm - maybe its a good idea to go ahead and incorporate the current fix (this pr) into the core.  Seems to be resolve some issues people are having: https://forum.arduino.cc/t/i2c-setclock-does-not-appear-to-be-standard-way-to-setclock/1147122/19

**Comment by aentinger** [comment]
As @facchinm is currently out-of-office I'll move ahead and merge this one.

**Pull request merged**
