### PR TITLE
Fix to allow absolute CAN bit rate error

### PR DESCRIPTION
**Pull request by fastbike**
https://github.com/arduino/ArduinoCore-renesas/issues/297

### CODE REVIEW

**Comment by fastbike** [comment]
It looks like some of the samples for the Portenza board errored out. I could look at these later today.

**Comment by per1234** [comment]
Thanks for your attention to the results of the continuous integration example sketch compilations @fastbike!

The compilation failure for the Portenta C33 board:

```text
/home/runner/Arduino/hardware/arduino-git/renesas/libraries/Arduino_CAN/src/R7FA6M5_CAN.cpp: In member function 'virtual bool arduino::R7FA6M5_CAN::begin(CanBitRate)':
/home/runner/Arduino/hardware/arduino-git/renesas/libraries/Arduino_CAN/src/R7FA6M5_CAN.cpp:153:120: error: cannot convert 'const CanBitRate' to 'uint32_t {aka long unsigned int}' for argument '1' to 'std::tuple<bool, long unsigned int, long unsigned int, long unsigned int> util::calc_can_bit_timing(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t)'
     util::calc_can_bit_timing(can_bitrate, F_CAN_CLK_Hz, TQ_MIN, TQ_MAX, TSEG_1_MIN, TSEG_1_MAX, TSEG_2_MIN, TSEG_2_MAX);
                                                                                                                        ^
```

Is not caused by the changes made in this pull request. The regression point is at https://github.com/arduino/ArduinoCore-renesas/commit/06bbfea395bf0f0509a37c4d96e42a59a670b0a5 from your previous pull request https://github.com/arduino/ArduinoCore-renesas/pull/296.

I'm sure it would be a welcome contribution if you wanted to investigate and submit a fix.

**Comment by aentinger** [comment]
>I'm sure it would be a welcome contribution if you wanted to investigate and submit a fix.

A single cast is needed.

**Comment by fastbike** [comment]
OK, I will see if I can find time tonight :)

**Comment by fastbike** [comment]
> Is not caused by the changes made in this pull request. The regression point is at [06bbfea](https://github.com/arduino/ArduinoCore-renesas/commit/06bbfea395bf0f0509a37c4d96e42a59a670b0a5) from your previous pull request #296.
> 
> I'm sure it would be a welcome contribution if you wanted to investigate and submit a fix.

How can I run the tests before submitting a PR ? 
Do I just open the example projects in the IDE for the other controller and compile ?

**Comment by per1234** [comment]
> How can I run the tests before submitting a PR ?

If you enable [**GitHub Actions**](https://docs.github.com/actions) in your fork, the compilations will run automatically every time you push a commit to your fork that modifies a relevant file.

I'll provide instructions you can follow to enable GitHub Actions:

1. Open the homepage of your fork in the browser:
   https://github.com/fastbike/ArduinoCore-renesas
1. Click the "**Actions**" tab at the top of the page.
1. Click the <kbd>**I understand my workflows, go ahead and enable them**</kbd> button.

> Do I just open the example projects in the IDE for the other controller and compile ?

You can do that. Make sure to select **Tools > Board > Arduino Renesas Portenta Boards > Arduino Portenta C33** from the Arduino IDE menus, and that your modifications are present in the "**Arduino_CAN**" library used by that board (which by default is under a different path than the library used by the UNO R4 boards since this repository is split into two separate platforms ("**Arduino UNO R4 Boards**", "**Arduino Renesas Portenta Boards**") for distribution, each platform with its own copy of the "**Arduino_CAN**" library.

Ideally you would install the ArduinoCore-renesas repository locally as an Arduino boards platform so that you can test within the full context, but that is a bit complicated to do (especially since the developers haven't provided documentation for the procedure) and probably not necessary in this particular case where you are only modifying the library code.

**Comment by aentinger** [comment]
If possible, @fastbike I'd prefer to have a separate PR fixing the regression for C33. Can you do this? If it's too much a bother please give me a ping and I shall fix it, it's a simple fix.

**Comment by aentinger** [comment]
Hi @fastbike :coffee: :wave: 

I've fixed the regression concerning the Portenta C33 in https://github.com/arduino/ArduinoCore-renesas/pull/300. Furthermore I have rebased your branch on `ArduinoCore-renesas:main` so that the fix is now included.

**Important**: Before you do anything, run the following command on your end: `git pull origin main --rebase`.

**Pull request closed without merging**
