### PR TITLE
add ping WiFiS3

### PR DESCRIPTION
**Pull request by paulvha**
see issues topic 251
needs to be used in combination with a pull request on bridge software.
the WifiCommands.h used to be a symbolic link but that was not pulled in. Hence it is now a seperate file.

regards,
Paul

### CODE REVIEW

**Comment by JAndrassy** [comment]
this core has 3 networking libraries so please add WiFiS3 into the title. (the other two are WiFi and Ethernet for Portenta C33)

**Comment by per1234** [comment]
Hi @paulvha. Thanks so much for your pull request!

Unfortunately, the **@[]()CLAassistant** bot has not been able to validate the pull request meets Arduino's Contributor License Agreement (CLA) requirement.

This is likely caused by the email address used in your local Git settings not being associated with your GitHub account. Please follow these instructions to resolve the issue:

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

Hopefully the check will automatically pass once that has been done. If not, please comment here and we will investigate.

**Comment by paulvha** [comment]
I have added paulvha@hotmail.com (it already had paulvha@outlook.com) and verified. set the default to hotmail.com. please anything else I can / need to do to perform a re-run. 
regards,
Paul

**Comment by paulvha** [comment]
included also WiFiTime() now. Somehow the changes in Wifi.cpp and Wifi.h are not taken into account when the test compile is done online

**Pull request closed without merging**
