### PR TITLE
Add new example (we'll need it in the fwuploader)

### PR DESCRIPTION
**Pull request by umbynos**
This example will help us to add support for certificate upload in the [fwuploader](https://github.com/arduino/arduino-fwuploader). It allows us to perform a file upload on the external QSPI of the Portenta C33 by using ymodem protocol. This way we can upload a certificate file using a [simple go program](https://github.com/arduino/ArduinoCore-mbed/tree/main/libraries/NDP/examples/Syntiant_upload_fw_ymodem/extra/syntiant-uploader).

It's based on [this other example](https://github.com/arduino/ArduinoCore-mbed/blob/main/libraries/NDP/examples/Syntiant_upload_fw_ymodem) and [this](https://github.com/bcmi-labs/ArduinoCore-renesas/tree/main/libraries/SSLClient/examples/CertificateUploader).

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @umbynos :coffee: :wave: 

Do we still need this or can this PR be closed?

**Comment by umbynos** [comment]
I added this because it's what we use internally in the fwuploader tool: https://github.com/arduino/portenta-c33-fwuploader-plugin/tree/main/sketches/certificate
I thought it would make sense to have this in the main core repository. But if you feel differently, please close it :smile:

**Comment by aentinger** [comment]
It may make sense to have it in the core. What doesn't make sense is to leave a PR open indefinitely :wink: . So I'd be open to merge. Can you confirm that the version in this PR is the latest one?

**Comment by umbynos** [comment]
I don't think it's the latest one, I'll update it

**Comment by aentinger** [comment]
I'll be closing this PR due to inactivity. @umbynos please feel free and reopen it if you'd like to update and merge this sketch.

**Pull request closed without merging**
