### PR TITLE
Fix RTC resetting after reboot

### PR DESCRIPTION
**Pull request by andreagilardoni**
This PR aims to fix the issue described here https://github.com/arduino/ArduinoCore-renesas/issues/181. 
The issue can be described as follow: When the board is reset, or powered off with VRTC powered, the RTC time value is reset.

### CODE REVIEW

**Comment by workgroupengineering** [comment]
Hi, is there an ETA of when this PR will be merged and published?

**Comment by andreagilardoni** [comment]
Hi @workgroupengineering, since this PR required the FSP core to be recompiled, we are testing this to check whether we have any issues on other components. If you want you can apply this patch on your local core and report to us if you find any issues.

**Comment by workgroupengineering** [comment]
Thanks for the reply, I'll try

**Comment by pennam** [comment]
Portenta C33 + USB cable plugged -> reset button :+1: 
Portenta C33 + Portenta breakout + CR2032 + USB cable -> reset button :+1: 
Portenta C33 + Portenta breakout + CR2032 + USB cable -> disconnect usb cable :+1:

**Comment by pennam** [comment]
Portenta C33 retest after force push :+1: 
UNO R4 Minima + USB cable plugged -> reset button :+1:  Thanks @aentinger 
UNO R4 WiFi + USB cable plugged -> reset button :+1: 
UNO R4 WiFi + USB cable plugged + external Vbat -> reset button :+1: 
UNO R4 WiFi + USB cable plugged + external Vbat -> disconnect usb cable :+1:

**Review by pennam — APPROVED** [review]
:ship:

**Pull request merged**
