### PR TITLE
WiFiS3 At improvements

### PR DESCRIPTION
**Pull request by andreagilardoni**
Improving the AT parsing function

### CODE REVIEW

**Comment by JAndrassy** [comment]
please add "WiFiS3" into the PR title

**Comment by pennam** [comment]
Testing core sketches using AT commands:
[OTA](https://github.com/arduino/ArduinoCore-renesas/blob/main/libraries/OTAUpdate/examples/OTA/OTA.ino) :+1: 
[StartCounter](https://github.com/arduino/ArduinoCore-renesas/blob/main/libraries/Preferences/examples/StartCounter/StartCounter.ino) :+1: 
[Prefs2Struct](libraries/Preferences/examples/Prefs2Struct/Prefs2Struct.ino) :+1:

**Comment by andreagilardoni** [comment]
Fixed the issue that was making the tests @pennam mentioned in the previous comment: https://github.com/andreagilardoni/ArduinoCore-renesas/blob/649ecb8b5fa2665fc555a1cd29440b85b6614cac/libraries/WiFiS3/src/Modem.cpp#L229
The issue is that we cannot check the response prompt in passthrough mode since we lack the knowledge of the previously sent command. The line will be preserved with a comment indicating that when solved this could help improving the reliability of the protocol, since it enforces a command to have a response with a matching prompt.

**Comment by pennam** [comment]
Testing core sketches using AT commands:

| Sketch   |      0.5.0      |  0.4.1 |
|----------|:-------------:|------:|
[OTA](https://github.com/arduino/ArduinoCore-renesas/blob/main/libraries/OTAUpdate/examples/OTA/OTA.ino) | :+1:| 
[StartCounter](https://github.com/arduino/ArduinoCore-renesas/blob/main/libraries/Preferences/examples/StartCounter/StartCounter.ino) |:+1:| 
[Prefs2Struct](libraries/Preferences/examples/Prefs2Struct/Prefs2Struct.ino) |:+1:| 
[SATSECertificate](libraries/SoftwareATSE/examples/SATSECertificate/SATSECertificate.ino) |:+1:| 
[SATSEPrivateKey](libraries/SoftwareATSE/examples/SATSEPrivateKey/SATSEPrivateKey.ino) |:+1:| 
[SATSERandomNumber](libraries/SoftwareATSE/examples/SATSERandomNumber/SATSERandomNumber.ino) |:+1: |
[SATSESerialNumber](libraries/SoftwareATSE/examples/SATSESerialNumber/SATSESerialNumber.ino) |:+1: |
[SATSESignAndVerify](libraries/SoftwareATSE/examples/SATSESignAndVerify/SATSESignAndVerify.ino) |:+1:| 
[WiFiWebServer](libraries/WiFiS3/examples/WiFiWebServer/WiFiWebServer.ino) |:+1: |
[WiFiWebClientSSL](libraries/WiFiS3/examples/WiFiWebClientSSL/WiFiWebClientSSL.ino) |:+1:|
[WiFiWebClientRepeating](libraries/WiFiS3/examples/WiFiWebClientRepeating/WiFiWebClientRepeating.ino) |:+1: |

**Review by pennam — APPROVED** [review]

**Pull request merged**
